title: Maitreya Suin # your name (or website title) here
logo: "/images/br_2c2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD Scholar (Computer Vision) 
  <br><br>
  <a href="https://maitreyasuin.github.io/pages/pubs"><big><u><b>Publications</b></u></big></a>
  <br><br>
  <a href="https://www.linkedin.com/in/maitreya-suin/"><b><small>LinkedIn</small></b></a>
  <br>
  <a href="https://scholar.google.com/citations?user=Yjf3OKcAAAAJ&hl=en"><small>Google-Scholar</small></a>
  <br>
  <a href="mailto:maitreyasuin21@gmail.com"><small>E-Mail</small></a>
  <br>
  <a href="https://maitreyasuin.github.io/files/CV_Maitreya_Suin.pdf"><small>CV</small></a>
  <br>
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
